name: ShadowBreach Scheduled Scraper

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:       # Allows manual trigger from GitHub UI

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: python shadowbreach_scraper.py

    - name: Commit and push results
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add results/*
        git commit -m "Update results at $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No changes"
        git push
